#!/usr/bin/env bash

set -uexo pipefail

# Replace stock mutter with patched build (Night Light EDID fallback, auto-rotate fix, 3x auto-scale fix)
dnf -y swap --repo='copr:copr.fedorainfracloud.org:lorbus:misc' \
    mutter mutter

# Replace stock iio-sensor-proxy with patched build (Do not exit based on sensor events workaround)
dnf -y swap --repo='copr:copr.fedorainfracloud.org:lorbus:misc' \
    iio-sensor-proxy iio-sensor-proxy

# Install additional fedora packages
ADDITIONAL_FEDORA_PACKAGES=(
    gnome-text-editor
    snapshot
    firefox
    gstreamer1-plugin-openh264
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-good

    gnome-shell-extension-appindicator
    gnome-shell-extension-blur-my-shell
    gnome-shell-extension-caffeine
    gnome-shell-extension-dash-to-dock
    gnome-shell-extension-gsconnect
    #gnome-shell-extension-just-perfection
    #gnome-shell-extension-nekotorch
    #gnome-shell-extension-network-displays
    gnome-shell-extension-screen-autorotate
    #gnome-shell-extension-weather-or-not

    # Default GNOME Shell Extensions
    # https://src.fedoraproject.org/rpms/gnome-shell-extensions
    gnome-shell-extension-apps-menu
    gnome-shell-extension-auto-move-windows
    gnome-shell-extension-drive-menu
    gnome-shell-extension-launch-new-instance
    gnome-shell-extension-light-style
    gnome-shell-extension-native-window-placement
    gnome-shell-extension-places-menu
    gnome-shell-extension-screenshot-window-sizer
    gnome-shell-extension-status-icons
    gnome-shell-extension-system-monitor
    gnome-shell-extension-user-theme
    gnome-shell-extension-window-list
    gnome-shell-extension-windowsNavigator
    gnome-shell-extension-workspace-indicator
)

dnf -y install --skip-unavailable \
    "${ADDITIONAL_FEDORA_PACKAGES[@]}"

dnf -y copr enable lorbus/calls
dnf -y install calls
dnf -y copr disable lorbus/calls

dnf -y copr enable lorbus/network-displays
dnf -y install gnome-network-displays gnome-network-displays-extension
dnf -y copr disable lorbus/network-displays
